Repository glpi-project/glpi-inventory-plugin, pull requests merged in 2022-06, with the labels that each got.

#123 Migration of inventory rules
  install/update.native.php
  install/update.php
  setup.php
Labels: enhancement

#131 Redirect plugin empty home page to more useful one
  front/menu.php
  inc/menu.class.php
Labels: ux

#135 fix(discovery): mark inventory as discovery mode
  inc/communicationnetworkdiscovery.class.php
Labels: bug

#139 fix(IHM): reduce click
  inc/taskjobview.class.php
Labels: enhancement

#140 feat(snmp): add count element in table on tab
  inc/iprange_snmpcredential.class.php
Labels: enhancement

#141 fix(refresh): fix unselected option
  js/taskjobs.js
Labels: bug

#134 Update net tasks log
  inc/communicationnetworkdiscovery.class.php
  inc/communicationnetworkinventory.class.php
Labels: bug, enhancement

#142 feat(ui): add menu icon
  inc/menu.class.php
Labels: ui

#145 feat(ui): harmonize color
  templates/submenu.html.twig
Labels: enhancement, ui

#146 fix(taskjoblog): prevent error on classname
  inc/taskjoblog.class.php
Labels: bug

#137 fix(job): fix empty job log
  front/task.form.php
  inc/iprange.class.php
  inc/statediscovery.class.php
  inc/stateinventory.class.php
  inc/task.class.php
  inc/taskjob.class.php
  js/taskjobs.js
  setup.php
Labels: bug

#150 Minor UI fix
  css/views.css
  inc/commonview.class.php
  inc/task.class.php
  inc/taskview.class.php
  js/taskjobs.js
Labels: enhancement, ui

#153 feat(core): add dashboard to main menu
  front/menu.php
  hook.php
  inc/dashboard.class.php
  inc/task.class.php
  install/update.php
  setup.php
Labels: enhancement, ui

#156 fix(migration): fix migration
  install/update.native.php
  install/update.php
  install/update.tasks.php
Labels: bug

#160 fix(display): correctly display last log
  inc/task.class.php
  js/taskjobs.js
Labels: bug

#155 Some dark theme fixes
  css/views.css
  inc/taskjobview.class.php
  inc/taskview.class.php
Labels: bug, ux

#162 Migrate agents cleanup configuration
  inc/config.class.php
  install/update.native.php
  install/update.php
  tests/Installation/DatabaseTestsCommons.php
Labels: bug

#164 fix(php): fix undefined index
  front/deploygroup.form.php
Labels: bug
